spring.application.name=demo

# MSSQL の接続URL
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=test;trustServerCertificate=true

# ユーザー名とパスワード
spring.datasource.username=アカウント名
spring.datasource.password=パスワード

# ドライバークラス
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.example.fullness.stationary.entity
mybatis.mapper-locations=classpath:mapper/*.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/fullness_ec
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
