spring.application.name=demo

mybatis.configuration.map-underscore-to-camel-case=true

# mybatis.type-aliases-package=com.example.mybatis.entity


spring.datasource.url=jdbc:postgresql://localhost:5432/fullness_ec
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
